services:
  - type: web
    name: youtube-monitor
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false

  - type: worker
    name: youtube-monitor-worker
    env: python
    plan: free
    buildCommand: ""
    startCommand: python monitor.py
